spring.application.name=payment-service

# application.properties
server.port=3006

# Base URL of this payment-service (for checkoutUrl)
app.ui.base-url=http://localhost:3006

# User Service Configuration
user.service.base-url=http://localhost:3000

# RazorPay Configuration
# Get your API keys from: https://dashboard.razorpay.com/app/keys
razorpay.key-id=<your-razorpay-key-id>
razorpay.key-secret=<your-razorpay-key-secret>
razorpay.currency=INR
razorpay.base-url=https://api.razorpay.com/v1

# YOU choose this string and reuse the same in Razorpay dashboard webhook config
razorpay.webhook-secret=<your-razorpay-webhook-secret>

# Admin user id (for wallet updates)
# Replace with your actual admin user ID from MongoDB
payment.admin.user-id=<your-admin-user-id>

# MongoDB Configuration
# Replace with your actual MongoDB connection string
# Format: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<database>?retryWrites=true&w=majority&appName=<AppName>
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/nexus_products?retryWrites=true&w=majority&appName=<AppName>

# OpenAPI spec JSON
springdoc.api-docs.path=/v3/api-docs
